### ISSUE TITLE
[ ✨Feat ] project 페이지 구현

### ISSUE THREAD

**Issue by jamooooong** [jamooooong/jamooooongPage#19]
# ✨Feature Issue
project page 구현
## To-do
- [ ] 프로젝트 페이지 구현
- [ ] 이미지가 첨부된 페이지 구현
- [ ] 라우팅 추가 될듯

**Comment by jamooooong** [comment]
![Rectangle 7 1png](https://github.com/user-attachments/assets/51bc6b9f-9430-4a1b-bf35-7e29155174f0)
![Rectangle 72](https://github.com/user-attachments/assets/b962b54c-847e-48bc-bb97-221c86b3e83f)
